name: main
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: xzn92/ntr-hr-build-environment:2026-01-08
    steps:
      - name: Rust env
        run: |
          ln -s /root/.rustup ~/.rustup
      - name: Compile NTR-HR
        run: |
          pushd ntr-hr
          MAKEFLAGS="USE_CLANG=1 USE_LTO=1" ./make.sh install
          popd
      - name: Prepare node
        run: |
          source /usr/share/nvm/init-nvm.sh
          nvm install node
          echo "$(dirname $(which node))" >> "$GITHUB_PATH"
      - uses: actions/upload-artifact@v4
        with:
          name: BootNTRSelector-PabloMK7-Banner.cia
          path: BootNTR-Bins/output/3ds-arm/BootNTRSelector-PabloMK7-Banner.cia
          compression-level: 0
